# Generated by Django 4.2.4 on 2023-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythird3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('pin_code', models.IntegerField(max_length=10)),
            ],
        ),
    ]
